inherit_from: base.yaml
experiment:
    num_train_workers: 1 #12
    batch_size: 1 #16
    experiment_name: anyplace_diffusion_molmocrop_vial_inserting
    run_name: anyplace_diffusion_molmocrop_vial_inserting
    meshcat_on: False
    resume: False
    num_iterations: 500000
    train:
        train_coarse_aff: False
        train_refine_pose: True
        train_success: False
        out_log_full: False
        out_log_coarse_aff: True
        out_log_refine_pose: True
        out_log_success: True

data:
    data_root: task_gpp_vial_plate_only
    dataset_path: vial_on_plate/task_name_vial_on_plate_chunked
    parent_mesh_dir: 
    child_mesh_dir: 
    load_full_pcd: False
    parent_crop: False
    gpp_crop: True
    shape_pcd_n: 2048
    parent_shape_pcd_n: 400
    child_shape_pcd_n: 200
    pose_perturb:
        use_small_rot_scale: False
        use_small_trans_scale: False
        rot_scale_deg: 360
        trans_scale: 0.48
    refine_pose:
        diffusion_steps: true
        n_diffusion_steps: 5
        parent_crop: False
        parent_crop_same_n: False
        vary_crop_size_diffusion: False
        interp_diffusion_traj: true
        precise_diff_prob: true
        parent_shape_pcd_n: 400
        child_shape_pcd_n: 200
        aug:
            rot_aug: 'yaw_rot'

optimizer:
    refine_pose:
        type: AdamW
        valid_opts:
        - Adam
        - AdamW
        use_schedule: true
        schedule:
            fixed_lr: false
            min_lr: 1.0e-06
            warmup_epochs: 50
        opt_kwargs:
            AdamW:
                lr: 0.0001
                weight_decay: 1.0e-01
                betas:
                - 0.9
                - 0.95

model:
    refine_pose:
        type: nsm_transformer 
        model_kwargs:
            nsm_transformer:
                n_queries: 1
                use_timestep_emb: True
                max_timestep: 5
                timestep_pool_method: meanpool  # meanpool, concat

loss:
    refine_pose:
        type: tf_chamfer
    tf_chamfer:
        l1: True
